services:

  postgres:
    image: postgres:15
    container_name: voting-postgres
    environment:
      POSTGRES_DB: votingdb
      POSTGRES_USER: voting
      POSTGRES_PASSWORD: voting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voting-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: voting-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - voting-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: voting-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - voting-network
volumes:
  postgres_data:

networks:
  voting-network:
